### ISSUE TITLE
Properties Panel Becomes Partially Inaccessible

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-properties-panel#115]
In some cases when there is not enough space on the screen the properties panel moves up and becomes partially inaccessible until the next render.

Before:

<img width="682" alt="chrome_FQlK7Wh0ud" src="https://user-images.githubusercontent.com/7633572/133764119-4696a344-90a3-42c9-abcb-bcfc1837f0a3.png">

After:

<img width="682" alt="chrome_3emKn3NRuZ" src="https://user-images.githubusercontent.com/7633572/133764142-54001e4d-a31b-4ee9-93ab-377e43650b4f.png">

# Reproduce

1. Select a call activity
2. Add out mappings until the properties panel starts to scroll
3. Set _Propagate all variables_ to true
4. Properties panel moves up

Related to https://github.com/bpmn-io/bpmn-properties-panel/pull/94#issuecomment-921627378
Related to camunda/camunda-modeler#2364

**Comment by pinussilvestrus** [comment]
I discovered this behavior with some other checkboxes as well. I'm pretty sure this is due to the hacky custom checkbox we have in place here. Chances are good this will be resolved during #90.

**Comment by MaxTru** [comment]
I just wanted to try to fix this by integrating https://github.com/bpmn-io/properties-panel/commit/49cfdde6e774d62c269eed0bfce0066ad1cd4076, however I cannot reproduce this bug :-) Maybe this goes to Windows folks @philippfromme ?
