### ISSUE TITLE
Timer event documentation link leads to "Page not found" for a brief period

### ISSUE THREAD

**Issue by chincholikarsalil** [bpmn-io/bpmn-properties-panel#123]
Issue reference: https://github.com/camunda/camunda-modeler/issues/2413
Comment reference: @MaxTru  https://github.com/camunda/camunda-modeler/issues/2413#issuecomment-919068364

__Describe the Bug__

On clicking the documentation link in the timer event, for a short period "page not found" message is displayed until it is redirected to the actual documentation page.

__Steps to Reproduce__

1. In the Modeler, open a new BPMN diagram for cloud and add a timer event.
2. Open the properties panel and click on the field Timer event.
3. Now click open the link "documentation: Timer events"
4. We could see that for a very short period "page not found" is displayed until the actual documentation page is displayed.

__Expected Behavior__

On clicking the link it should directly lead to the documentation page without any error page popping up.

__Environment__

OS: [Windows 10]
Camunda Modeler Version: [4.10.0]
Execution Platform: [Camunda Cloud]

**Comment by chincholikarsalil** [comment]
According to @MaxTru's comment on the original issue, there is a small fix.
Is it okay if I try to fix it?

**Comment by nikku** [comment]
@chincholikarsalil Please go ahead!

**Comment by pinussilvestrus** [comment]
Related to https://github.com/camunda/camunda-modeler/issues/2413
