### ISSUE TITLE
Timer props set $attr property

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-properties-panel#127]
__Describe the Bug__

When I switch the timer type to `<none>`, it sets a property within $attr as on the screenshot:

![image](https://user-images.githubusercontent.com/28307541/136024565-b6376067-e592-4c57-977e-a26e985d742e.png)

__Steps to Reproduce__

1. Create a timer event
2. Switch event type to cycle and back to `<none>`
3. now this happens

__Expected Behavior__

There should be no props in $attr.

__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

---

Discovered in https://github.com/bpmn-io/bpmn-properties-panel/pull/120

**Comment by barmac** [comment]
So it seems we set `''` property within the timer props: https://github.com/bpmn-io/bpmn-properties-panel/blob/main/src/provider/bpmn/properties/TimerProps.js#L93

**Comment by natalson** [comment]
I would like to work on this. Please assign it to me.

**Comment by barmac** [comment]
No need to assign. Feel free to prepare a PR.

**Comment by barmac** [comment]
What we will need is:

1. Fix for the bug.
2. A test case which confirms the property is not assigned.
