### ISSUE TITLE
Add Element Template Properties for Inputs, Outputs, Connector Inputs/Outputs, and Errors

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-properties-panel#147]
Add element template properties for inputs, outputs and errors reusing existing implementations.

# Input Parameters

* reuse existing group and entry
* display template label or binding name as title
* do not display name entry
* display description
* display _Local Variable Assignment_ toggle
* implement also for `camunda:Connector`

# Output Parameters

* reuse existing group
* display description
* display _Process Variable Assignment_ toggle
* display _Assign to process variable_
* implement also for `camunda:Connector`

# Errors

* reuse existing group and entry
* disable _Throw expression_ entry
* do not display _Global error referenced_ entry

**Comment by barmac** [comment]
Added `camunda:Connector` to the list.

**Comment by philippfromme** [comment]
Follow-up issue regarding connectors: https://github.com/bpmn-io/bpmn-properties-panel/issues/157
