### ISSUE TITLE
Support calledDecision for businessRuleTask

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-properties-panel#153]
__Is your feature request related to a problem? Please describe.__

In Camunda Cloud `1.3.0`, we will support evaluating DMN decisions in Zeebe from BPMN using a business rule task. The Camunda modeler should allow defining the new properties of a business rule task.  

__Describe the solution you'd like__

For a business rule task,
* a user can choose between the implementation as a job worker (the only option for CC version `1.1` and `1.2`) and the evaluation of a DMN decision within Zeebe (that can be the new default option for version `1.3+`)
* if the user selects the evaluation of a DMN decision then the modeler should show the following properties:
  * new property `decisionId` to define the ID of the decision that is evaluated - it has either a static value or an expression
  * new property `resultVariable` to define the variable name of the decision result (the default value could be the same as `decisionId`)
  * no properties like `Binding`, `Tenant Id` or `Map Decision Result` are supported (from Camunda Platform)
  
__Describe alternatives you've considered__

None.

__Additional context__

Sample XML with the new properties:

```
    <bpmn:businessRuleTask id="chooseDish" name="Choose Dish">
      <bpmn:extensionElements>
        <zeebe:calledDecision decisionId="dish" resultVariable="dish" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_0ixwjoa</bpmn:incoming>
    </bpmn:businessRuleTask>
```

Related issue in Zeebe: https://github.com/camunda-cloud/zeebe/issues/8060
Child of camunda/camunda-modeler#2524

**Comment by MaxTru** [comment]
# Async KickOff

The following concept outlines the basic work scope for this issue.

## Sketch for the implementation

(!) Note that all labels are WIP, sketch is just to clarify the basic concept

### Add a new section "implementation"

![Screenshot_20211104_130325](https://user-images.githubusercontent.com/42800119/140310271-97ffc3d2-047e-455a-b26c-f3cb4f790ceb.png)

### Only show "Task definition" if implementation==jobWorker

![Screenshot_20211104_130422](https://user-images.githubusercontent.com/42800119/140310388-c741eeb5-35db-4309-8e3c-cb138d04d243.png)

### New section "Called Decision" / only show if implementation==decision

![Screenshot_20211104_130511](https://user-images.githubusercontent.com/42800119/140310489-e8661c42-1527-4a4c-8ba1-e036ccb40b9f.png)

## Approach

* Max will perform implementation
* Max will provide artifact to 
  * @saig0 for review from Zeebe side (once we integrated into Camunda Modeler)
  * @andreasgeier for design review
  * @bpmn-io/modeling-dev for engineering review

## Ressource

https://miro.com/app/board/o9J_llsWdQ4=/

**Comment by nikku** [comment]
Makes sense to me. I like especially that we put the priority on linking a decision in the business rule task, rather than implementing a service behind it.

**Comment by saig0** [comment]
@MaxTru looks good :+1: 

One minor suggestion: in the dropdown, use "DMN decision" instead of "Decision". I don't expect other types of decisions but DMN is a prominent term. For Camunda Platform 7, this option is just called "DMN".

**Comment by andreasgeier** [comment]
Sounds good! (Agreed by async kickoff)

If decision will be the default/our recommendation for Zeebe 1.3+, I would show it as the first option in the dropdown:
- \<none\>
- DMN decision
- Job worker

The label for the corresponding section could be "Called DMN decision" then.
