### ISSUE TITLE
Update Element Template Feature broken

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-properties-panel#165]
__Describe the Bug__

Update Element Template Feature broken

__Steps to Reproduce__

![ETBug](https://user-images.githubusercontent.com/42800119/140985950-542aa9b8-7009-480c-bc6a-860e47b8414c.gif)

1. Have multiple templates from Cawemo synced
2. Apply one template
3. => note that even though the template does not have a newer version, one can apply a new version. => the actual template is changed

(It seems the update logic does not filter on template id?)

__Expected Behavior__

Update element template logic only available for template with the same ID (and multiple versions)

__Environment__

https://github.com/bpmn-io/bpmn-properties-panel/pull/161

**Comment by barmac** [comment]
It seems that we'd need to re-render the templates group whenever templates are changed.
