### ISSUE TITLE
Improve the `npm run start:templates` fixture

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-properties-panel#179]
__What should we do?__

The example should show all or most of the element templates features:

* [ ] template available -> consider adding a simple template selection mechanism
* [ ] template not found
* [ ] update available
* [ ] template applied
* custom properties:
  * [ ] camunda:input
  * [ ] camunda:output
  * [ ] camunda:in
  * [ ] camunda:out
  * [ ] bpmn property
  * [ ] camunda:property
* scopes:
  * [ ] bpmn:Error
  * [ ] camunda:Connector
* [ ] constraints (validation)
* [ ] description
* [ ] label

__Why should we do it?__

We want to easily try out new features and bugfixes.

**Comment by MaxTru** [comment]
This is great and would make testing much easier
