### ISSUE TITLE
Implement version tag property

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-properties-panel#18]
We should add the `Version Tag` property to the existing general group for processes and collaborations

![image](https://user-images.githubusercontent.com/9433996/125407728-6f8f0c00-e3ba-11eb-92f8-74feb6639a65.png)

**Comment by pinussilvestrus** [comment]
I think we should simply stick to the existing group & UI.

/cc @andreasgeier & @MaxTru

**Comment by MaxTru** [comment]
> I think we should simply stick to the existing group & UI.
> 
> /cc @andreasgeier & @MaxTru

I agree
