### ISSUE TITLE
Implement Camunda Platform Properties

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-properties-panel#2]
# Implement Camunda Platform Properties

## Goal

As a developer implementing BPMN, I want to use Camunda Platform specific properties in the properties panel.

## What should we do?

Migrate groups with Camunda Platform properties.

* [x] #10
* [x] Migrate general group
  * [x] id _part of BPMN props_
  * [x] name _part of BPMN props_
  * [x] process props _part of BPMN props_
  * [x] #18
  * [x] executable _part of BPMN props_
  * [x] ~~element template~~ **This will be implemented separately; outside of the scope.**
* [x] #36
  * [x] Task priority
* [x] #38
  * [x] Async before
  * [x] Async after
  * [x] Exclusive
  * [x] https://github.com/camunda/camunda-bpmn-js/issues/29
  * [x] https://github.com/camunda/camunda-bpmn-js/issues/30
* [x] #28
  * [x] Job priority
  * [x] Job retry time cycle
* [x] #12
  * [x] Candidate starter groups
  * [x] Candidate starter users
* [x] #19
  * [x] History time to live
* [x] #22
  * [x] IsStartableInTasklist
* [x] Migrate documentation group
  * [x] Element documentation
  * [x] Process documentation
* [x] #25
* [x] #23
  * [x] field name
  * [x] field type
  * [x] field value
* [x] #32
  * **Not sure if this belongs to Camunda Platform properties. This is more like BPMN general props but only in the implementation phase.**
* [x] Migrate details group **Each of the items should become a separate group. "Details" is too generic.**
  * [x] #41
  * [x] #43
  * [x] #47
  * [x] #55
  * [x] Event props (several props inside, cf. BPMN provider?)
    * [x] #68
    * [x] Error Event Definition
    * [x] #69
    * [x] #70
    * [x] #71
    * [x] #50
    * [x] #78
  * [x] #51
  * [x] #52
  * [x] #45
  * [x] #62
* [x] https://github.com/bpmn-io/properties-panel/issues/92
* [x] #84
  * [x] Loop cardinality
  * [x] Completion condition
* [x] #85
  * [x] Collection
  * [x] Element variable
  * [x] multiInstance asyncBefore
  * [x] multiInstance asyncAfter
  * [x] multiInstance exclusive
  * [x] multiInstance retry time cycle
* [x] #89
  * [x] In mapping
  * [x] Out mapping
* [x] Migrate form group
  * [x] #91
  * [x] #93
    * [x] field type
    * [x] field label
    * [x] default value
    * [x] field id
    * [x] value (for enums)
    * [x] constraint (validation)
    * [x] property
  * [x] https://github.com/bpmn-io/bpmn-properties-panel/issues/110
  * [x] https://github.com/camunda/camunda-bpmn-js/issues/46
  * [x] https://github.com/camunda/camunda-bpmn-js/issues/48
  * [x] #96  (new)
* [x] #48
  * [x] listener props
  * [x] listener details
  * [x] listener fields
  * [x] Migrate field injection inside listeners group:
    * [x] field name
    * [x] field type
    * [x] field value
* [x] #106
* [x] #54
  * [x] Input
  * [x] Output
* [x] #99
  * [x] Behavior that cleans up errors if implementationType is switched away from `external`
* [x] #101
  * [x] <del>connector details</del> (part of implementation group)
  * [x] input ==> preferably only re uses existing Inputs props
  * [x] output ==> preferably only re uses existing Outputs props

## Why should we do it?

We want to use the properties panel in Camunda Modeler / Camunda Platform BPMN tab.

## Potential for user tests

Once we implement a significant number of Camunda Platform properties, we can test their discoverability.

Maybe we want to re-arrange the items.

Update @pinussilvestrus (22nd July): We want to do it rather sooner than later (cf. https://github.com/bpmn-io/internal-docs/issues/330)

## How to proceed

Because the list is so long, I have decided to not create issue for each group up front. Let's keep it tidy as the list already allows to track the progress. 

Here's the flow how to work on this epic:

1. Pick up a group or a selected item from the group. 
2. Convert it to an issue using the recent GitHub feature (issue from list item).
3. Implement it. Once the issue is closed, GitHub will automatically mark the item as done.

To clarify basic questions during the translation from old to new properties panel, please check the [Summary of principles for current Properties Panel development](https://github.com/camunda/camunda-modeler-design/tree/main/guidelines#summary-of-principles-for-current-properties-panel-development)

About the structure of the new panel, please check https://github.com/camunda/camunda-modeler-design/issues/27 

## Context

* [Properties panel vision](https://github.com/camunda/camunda-modeler-design/blob/main/visual-ide/PROPERTY_PANEL.md)
* [UX guidance for sections](https://github.com/camunda/camunda-modeler-design/issues/27)

**Comment by pinussilvestrus** [comment]
Is this list already complete or WIP?

**Comment by barmac** [comment]
Still WIP. I am looking into this tomorrow.

**Comment by pinussilvestrus** [comment]
Mh, maybe there are some more from other tabs, e.g. Listeners or forms

![image](https://user-images.githubusercontent.com/9433996/124489044-db68e780-ddb0-11eb-8dba-12fc3727f872.png)

![image](https://user-images.githubusercontent.com/9433996/124489069-e0c63200-ddb0-11eb-9e81-f7a037f08073.png)

**Comment by barmac** [comment]
I have updated the list with the remaining properties. This should be complete now.

**Comment by MaxTru** [comment]
Should we in the epic also indicate how the structure changes with the implementation? (I think this mainly affects the `details` group)

**Example:** I think the `Details` Group should be split up.

**Why:**
* The new properties panel has the groups collapsed per default. Data Markers would show if a group is filled or not.
* If therefore makes sense to make the groups as small as possible (combining only what from an implementation perspective belongs together)
* I think a generic label as-is (`details`) is not helpful from a UX perspective / does not guide the user

**as-is**
```
Migrate details group
 Service Task delegate props (several props inside)
 User Task props (several props inside)
 Script Task props
 Link props
 Call Activity props
 Event props (several props inside)
 Error props
 Conditional props
 Start Event initiator
```

**to-be (example)**
| Old structure group | Old structure item  | New structure group |
| ------------- | ------------- | ------------- |
| Details  | Service Task Delegate  | Delegate  |
| Details  | User Task Props  | User Assignment  |
| Details  | Script Task Props  | Script  |
| Details  | Link props  | Link  |
| Details  | ... | ... |
| Details  | ... | ... |

**Comment by barmac** [comment]
Indeed, _details_ is a generic name which could be replaced by specific names related to the edited properties. I've updated the issue accordingly. Let's decide on the exact names during the implementation, though.

**Comment by andreasgeier** [comment]
I added the reference to the [Summary of principles for current Properties Panel development](https://github.com/camunda/camunda-modeler-design/tree/main/guidelines#summary-of-principles-for-current-properties-panel-development) in the issue section "How to proceed". Please consider.

**Comment by andreasgeier** [comment]
I added the reference: [Properties structure for new properties panel Camunda Scope](https://github.com/camunda/camunda-modeler-design/issues/27) in the issue section "How to proceed". Please consider.

**Comment by MaxTru** [comment]
To consider for later on improvements: https://github.com/camunda/camunda-modeler/issues/2378

**Comment by andreasgeier** [comment]
Today we reviewed the UI of nested lists and agreed on the solution.
Participants: @barmac @MaxTru @volkergersabeck @philippfromme @andreasgeier 

We decided to use the default nested list (second level almost equal to first level) on all places except for variable assignment type:list. There, we use a specific pattern without expanding/collapsing list items but showing a single input field only.

Find all cases in the prototype: https://fluffy-fiesta-212e1c7c.pages.github.io/prototypes/visual-ide/v12/

default nested list:

![Screen Shot 2021-08-09 at 16 56 56](https://user-images.githubusercontent.com/938244/128727420-da1d2d73-a72d-436b-8e38-f10b70734f67.png)

single input list:

![Screen Shot 2021-08-09 at 16 57 58](https://user-images.githubusercontent.com/938244/128727625-b1e3b77a-6a49-408e-90b2-9635f2a13124.png)

**Comment by barmac** [comment]
Summary of the meeting @pinussilvestrus, @MaxTru, and I had today:

* The list entry is blocking so we prioritise it over the templates topic.
* Max and Niklas will pick up the event props as the next topics.
* We have a common understanding on how we want to approach the templates topic later on:
  * The templates logic (setting the properties) will probably be a 1:1 migration.
  * There will be a templates provider of lower priority than the Camunda Platform provider. It will re-adjust the groups and entries according to the templates logic.

**Comment by barmac** [comment]
For the compensation, note that there is a bug ticket in Camunda Modeler repo: https://github.com/camunda/camunda-modeler/issues/2397

**Comment by barmac** [comment]
I've checked some of the places where the list ordering is relevant for the execution.

Found:
* `camunda:errorEventDefinition`s are evaluated in order as in XML; thus it's relevant for the execution which expression is first
* In case of camunda:inputOutput, only the first syntax error in an expression is reported by the engine; XML order matters

**Comment by barmac** [comment]
I've added Task listener as this can be implemented separately from Execution listener.

**Comment by barmac** [comment]
![giphy.gif](https://media.giphy.com/media/lD76yTC5zxZPG/giphy.gif)

It's hard to believe but we have finished all of the tasks in this issue. Thanks everyone for collaboration!

**Comment by andreasgeier** [comment]
That achievement is worth a celebration 🍾
