### ISSUE TITLE
Description style not as expected

### ISSUE THREAD

**Issue by andreasgeier** [bpmn-io/bpmn-properties-panel#202]
__Describe the Bug__

The style of descriptions is not as expected.

__Steps to Reproduce__

1. Open the Modeler with the new BPMN properties panel
2. Create a timer start event
3. Select a timer type
4. See description below the value input

<img width="427" alt="Screen Shot 2021-11-25 at 12 25 43" src="https://user-images.githubusercontent.com/938244/143433447-b4b623c5-a4b7-4a5c-ba7c-a9a42ead37ca.png">

__Expected Behavior__

Descriptions and links should look as defined in the [prototype v16](https://fluffy-fiesta-212e1c7c.pages.github.io/prototypes/visual-ide/v16/) (Task "Custom form elements" > Section "Custom form: input"):

<img width="405" alt="Screen Shot 2021-11-25 at 15 08 12" src="https://user-images.githubusercontent.com/938244/143455945-0010cca0-35ff-4513-a25f-76f893cdbba9.png">

**Comment by pinussilvestrus** [comment]
I think the [description styles](https://github.com/bpmn-io/properties-panel/blob/main/assets/properties-panel.css#L362) are basically there, but currently don't work for more complex description components (more than just text)

![image](https://user-images.githubusercontent.com/9433996/143463768-65450851-19c0-456c-b76b-23ae4752942c.png)

**Comment by MaxTru** [comment]
Fixed upstream via https://github.com/bpmn-io/properties-panel/pull/121
