### ISSUE TITLE
Executeable checkBox value change cannot be undone

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-properties-panel#21]
__Describe the Bug__

Executeable checkBox value change cannot be undone.

__Steps to Reproduce__

1. Checkout https://github.com/bpmn-io/bpmn-properties-panel/commit/9e98cf089f2c303d76d8a21a5a50fd1f5df5df76 of this repo
2. Run `npm start`
3. Select the process
4. Set the `Executeable` checkbox in the General group
5. Keyboard input `CTRL + Z` for undo
6. ==> Nothing happends

__Expected Behavior__

Undo works for checkbox

__Environment__

- Host (Browser/Node version), if applicable: Chrome 91
- OS: Linux
- Library version: https://github.com/bpmn-io/bpmn-properties-panel/commit/9e98cf089f2c303d76d8a21a5a50fd1f5df5df76

**Comment by MaxTru** [comment]
Hi @pinussilvestrus , can you please try to re-produce. This is tested in the test-suite, still I observe this behavior. Do I miss something?

**Comment by pinussilvestrus** [comment]
I was able to reproduce it on `main`. It seems like native undo/redo is not working for the checkbox input field while on focus. The focus is also not visible. Once you set the focus to something different (e.g. by clicking the canvas), undo/redo is working again.

![Kapture 2021-07-13 at 13 59 09](https://user-images.githubusercontent.com/9433996/125447920-157ceeba-6f6a-4d09-8891-ebdc51e816cb.gif)

**Comment by MaxTru** [comment]
Thanks for the test - moving to backlog
