### ISSUE TITLE
Linking `@bpmn-io/properties-panel` locally is not working properly

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-properties-panel#27]
__Describe the Bug__

When working with this and the upstream library [`bpmn-io/properties-panel`](https://github.com/bpmn-io/properties-panel) locally, I receive an error when starting the tests in this project.

```error
TypeError: Cannot read property '__H' of undefined
    at m (hooks.module.js?cb90:1)
    at p (hooks.module.js?cb90:1)
    at l (hooks.module.js?cb90:1)
    at p.PropertiesPanel [as constructor] (PropertiesPanel.js?acad:76)
    at p.M [as render] (preact.module.js?da65:1)
    at I (preact.module.js?da65:1)
    at m (preact.module.js?da65:1)
    at I (preact.module.js?da65:1)
    at m (preact.module.js?da65:1)
    at I (preact.module.js?da65:1)
```

__Steps to Reproduce__

In a local copy of `bpmn-io/properties-panel`
1. npm run build
2. yarn link

In a local copy of `bpmn-io/bpmn-properties-panel`
1. yarn link @bpmn-io/properties-panel
2. npm start
3. error appears

__Expected Behavior__

Linking dependencies + starting test suite should work as expected.

__Environment__

- Host (Browser/Node version), if applicable: Chrome 91.0.4472.114
- OS: macOS 10.15
- Library version: `main` branch

**Comment by nikku** [comment]
I'll look into this issue tomorrow. Maybe there is a quick fix.

**Comment by nikku** [comment]
Fixed via https://github.com/bpmn-io/bpmn-properties-panel/pull/29. I did also lay out an alternative for your consideration.

**Comment by pinussilvestrus** [comment]
Nice, thanks!
