### ISSUE TITLE
Implement Timer Definition props

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-properties-panel#4]
__What should we do?__

We should add the timer definition properties inside a new group "Timer Definition" (or some other name). That's how they look like in the [old Zeebe properties panel](https://github.com/camunda/camunda-bpmn-js/blob/main/lib/camunda-cloud/features/properties-provider/parts/TimerEventProps.js). Validation ("must provide value") is out of scope here, will be fixed via linting.

![image](https://user-images.githubusercontent.com/9433996/120981903-6934c100-c778-11eb-9ba6-4a396f037a73.png)

__Why should we do it?__

Child of bpmn-io/bpmn-properties-panel#3

**Comment by MaxTru** [comment]
Sketch solution
![timerEventDefinitions](https://user-images.githubusercontent.com/42800119/124559336-e4eb6180-de3b-11eb-98cf-8b325da5713f.gif)

**Comment by MaxTru** [comment]
Closed via https://github.com/bpmn-io/bpmn-properties-panel/pull/8
