### ISSUE TITLE
Provide a description for Timer Definitions

### ISSUE THREAD

**Issue by andreasgeier** [bpmn-io/bpmn-properties-panel#5]
__Is your feature request related to a problem? Please describe__

Help users to fill in a value for a timer definition.

__Describe the solution you'd like__

@jakobfreund proposed a hint like this

![Screen Shot 2021-06-15 at 15 18 56](https://user-images.githubusercontent.com/938244/122059522-03d27700-cded-11eb-9a60-932c2d4c25ea.png)

Link to docs: https://docs.camunda.io/docs/reference/bpmn-processes/timer-events/timer-events#time-duration 

__Describe alternatives you've considered__

Leave as-is

__Additional context__

Please note: for now, we could use the input description to provide that information. Later this might be replaced by better contextual help as part of the prop panel redesign (not yet in scope).

**Comment by MaxTru** [comment]
Closed via https://github.com/bpmn-io/bpmn-properties-panel/pull/8
