### ISSUE TITLE
Remove empty space after the last Group/section in the new Properties panel

### ISSUE THREAD

**Issue by GeethaParthasarathy** [bpmn-io/bpmn-properties-panel#60]
__Describe the Bug__

There is an empty space after the last field in the properties panel which cannot be accessed for any purpose and it needs to be removed.

__Steps to Reproduce__

1.Open the properties panel for a process.
2.Try to expand the Element documentation field.
3. We could see that an empty field space appears after expanding the above field and we could not access it for any purpose.
This issue occurs also in the gateway/task/event's properties panel.

__Expected Behavior__

The empty space needs to be removed .

__Environment__

- OS:  Windows 10
- Library version: nightly version 4.10.0

https://user-images.githubusercontent.com/85225325/128330805-c6cbadde-9431-4b47-b075-4cce44685a07.mp4

**Comment by pinussilvestrus** [comment]
Seems like a minimal UI issue. @andreasgeier can you verify that? 

<img width="490" alt="Bildschirmfoto 2021-08-05 um 13 06 35" src="https://user-images.githubusercontent.com/9433996/128340391-66dbd091-36dd-4600-98a0-32bdb9a8cb21.png">

**Comment by andreasgeier** [comment]
This is intended and a natural part of the UI pattern. The properties panel is a panel (or slider or drawer or however you call such a view) and consumes its area regardless of the content.

Closed as won't fix.
